import './globals.css'
import Header from "@/app/components/Header";
import { Mulish } from 'next/font/google'
import Footer from "@/app/components/Footer";

// If loading a variable font, you don't need to specify the font weight
const mulish = Mulish({
    weight: ['300', '400', '500', '600', '700', '800', '900'],
    subsets: ['latin'],
    display: 'swap',
})
export const metadata = {
  title: 'My NextJs App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={mulish.className}>
      <Header />
      {children}</body>
      <Footer />
    </html>
  )
}
